### ISSUE TITLE
Python write support 

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#23]
### Feature Request / Improvement

This is a placeholder ticket for implementing write support for PyIceberg.

Since we don't want PyIceberg to write the actual data, and only handle the metadata part of the Iceberg table format, we need to get an overview of the frameworks we most likely want to integrate with (PyArrow, Dask (fastparquet?), etc).

I would suggest the following first steps to keep it simple: Write using PyArrow (since that's the most commonly used FileIO) and start with unpartitioned tables.

What we need:

- [x] Avro write support: https://github.com/apache/iceberg/issues/7255
- [x] Write files and extract statistics: https://github.com/apache/iceberg/issues/7256
- [ ] Ability to alter the Manifest JSON: https://github.com/apache/iceberg-python/issues/22
- [x] Proper integration tests between Java and Python: https://github.com/apache/iceberg/pull/6398

**Comment by mgmarino** [comment]
It looks like this is partially done (🎉), but writing to parquet files is not yet supported even though the associated ticket is closed? Am I reading this correctly? Thanks!

**Comment by Fokko** [comment]
@mgmarino Writing is part of https://github.com/apache/iceberg-python/pull/41 👍  Writing the parquet file is actually quite trivial.
